### ISSUE TITLE
Issue with Case Sensitivity Between config.yml and ConfigManager.kt

### ISSUE THREAD

**Issue by lin-ion** [Elysium-7/Fabricord#2]
The key string in `config.yml` is `Webhook_URL`. However, `ConfigManager.kt` is `WebHook_URL`. 

https://github.com/KT-Ruxy/Fabricord/blob/f7ad91ff3ebe806614f067964537b120bcf3af32/src/main/kotlin/com/inf_ruxy/fabricord/util/ConfigManager.kt#L169-L171

https://github.com/KT-Ruxy/Fabricord/blob/f7ad91ff3ebe806614f067964537b120bcf3af32/src/main/resources/config.yml#L38-L41

So the following error was output

```md
[19:12:43] [Server thread/ERROR]: Webhook URL is not configured or blank.
[19:12:43] [Server thread/INFO]: <me> some messages
```

Changing the key in `config.yml` to `WebHook_URL: "https://..."` resolved the issue.

I really like the style of `modern`. Thank you.

**Comment by ririf4** [comment]
I am very sorry for the delay in getting back to you.
 I will fix and release this ASAP.
 I apologize for the inconvenience.
