### ISSUE TITLE
1.21?

### ISSUE THREAD

**Issue by Legendmanj** [Elysium-7/Fabricord#3]

**Comment by ririf4** [comment]
Yeah, I'm very happy!
 I think I'll release 1.20.4 and 1.20.6 at the same time!

**Comment by Legendmanj** [comment]
> Yeah, I'm very happy! I think I'll release 1.20.4 and 1.20.6 at the same time!

what about 1.21? 
good to know but please mind releasing 1.21 version
thankyou

**Comment by ririf4** [comment]
I intend to release 1.20.4, 1.20.6 and 1.21 at the same time!

**Comment by Legendmanj** [comment]
> I intend to release 1.20.4, 1.20.6 and 1.21 at the same time!

thankyou so much, love you
