### ISSUE TITLE
Fabricord for 1.21.1 from Modrinth not compatible with 1.21.1

### ISSUE THREAD

**Issue by CreeperHaed** [Elysium-7/Fabricord#5]
So what is happening is that the 1.21.1 Version from Modrinth does not work with 1.21.1

![grafik](https://github.com/user-attachments/assets/4ca36c9b-55f5-4484-a1fc-38c22d00ebb3)

`A potential solution has been determined, this may resolve your problem:`
`         - Replace mod 'Fabriord' (fabriord) 4.0.1 with any version that is compatible with:`
`                 - minecraft 1.21.1`
`More details:`
`         - Mod 'Fabriord' (fabriord) 4.0.1 requires any version between 1.21.3 (inclusive) and 1.22- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!`
`        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.9.jar:?]`
`        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.9.jar:?]`
`        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.9.jar:?]`
`        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.9.jar:?]`
`        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]`
`        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]`
`        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:1.0.1]`

And it calls itself "Fabriord"

**Comment by ririf4** [comment]
These were caused by errors in the metafile. A fix will be made today (6 Nov). Thank you for your report.
